version: 2

dependencies:
    override:
        - sudo pip install awscli
deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync build s3://www.georgeperry.info --region=eu-west-1 --delete --acl public-read;
